control_dt: 0.02

num_actions: 32

msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

# Joint to motor index mapping for Taks_T1 (32 DOF)
joint2motor_idx: [0, 1, 2, 3, 4, 5,       # left leg (6)
                 6, 7, 8, 9, 10, 11,      # right leg (6)
                 12, 13, 14,              # waist (3)
                 15, 16, 17, 18, 19, 20, 21,  # left arm (7)
                 22, 23, 24, 25, 26, 27, 28,  # right arm (7)
                 29, 30, 31               # neck (3)
                 ]

kps: [100, 100, 100, 150, 40, 40,   # left leg
      100, 100, 100, 150, 40, 40,   # right leg
      150, 150, 150,                # waist
      40, 40, 40, 40, 20, 20, 20,   # left arm
      40, 40, 40, 40, 20, 20, 20,   # right arm
      20, 20, 20]                   # neck

kds: [2, 2, 2, 4, 2, 2,   # left leg
      2, 2, 2, 4, 2, 2,   # right leg
      4, 4, 4,            # waist
      5, 5, 5, 5, 1, 1, 1,  # left arm
      5, 5, 5, 5, 1, 1, 1,  # right arm
      2, 2, 2]            # neck

default_angles: [-0.2, 0.0, 0.0, 0.4, -0.2, 0.0,   # left leg
                -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,    # right leg
                0, 0, 0,                           # waist
                0, 0.4, 0, 0.8, 0.0, 0.0, 0.0,     # left arm
                0, -0.4, 0, 0.8, 0.0, 0.0, 0.0,    # right arm
                0.0, 0.0, 0.0                      # neck
                ]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.5
